services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-gateway-app
    env_file:
      - .env
    environment:
      PORT: ${PORT:?PORT is required}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:?DB_USER is required}
      DB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is required}
      DB_NAME: ${DB_NAME:?DB_NAME is required}
      DB_SSLMODE: ${DB_SSLMODE:?DB_SSLMODE is required}
      JWT_PUBLIC_KEY_PATH: /app/certs/keys/jwt-public.pem
      ACCESS_TOKEN_COOKIE_NAME: ${ACCESS_TOKEN_COOKIE_NAME:?ACCESS_TOKEN_COOKIE_NAME is required}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./certs:/app/certs:ro
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: payment-gateway-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:?DB_NAME is required}
      POSTGRES_USER: ${DB_USER:?DB_USER is required}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is required}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:?DB_USER is required} -d ${DB_NAME:?DB_NAME is required}",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: payment-gateway-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6378:6378"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
